version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  valetudomap:
    build: 
      context: .
      network: host
    ports:
      - 8081:3000
    environment:
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
      - DATABASE_URL=postgres://postgres:example@db/db_name

volumes:
  db-volume: